# This is a basic workflow to help you get started with Actions

name: screenshot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: lixxbox/mainsail-docs
        path: docs
    - uses: lixxbox/jekyll-screenshot-github-action@master
    - uses: actions/upload-artifact@v3
      with:
       name: screenshots
       path: /home/runner/work/_temp/_github_home/screenshot*.jpeg
